# Generated by Django 3.0.3 on 2020-03-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type_name_ru', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PythonModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='Python_models/')),
                ('model_name', models.CharField(max_length=200)),
                ('count_params', models.IntegerField()),
                ('is_universal', models.BinaryField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.ModelsTypes')),
            ],
        ),
        migrations.CreateModel(
            name='ScoresTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
                ('type_name_ru', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_uid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.PythonModels')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.Tests')),
            ],
        ),
        migrations.CreateModel(
            name='ModelsScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.PythonModels')),
                ('score_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeler.ScoresTypes')),
            ],
        ),
    ]
