# Generated by Django 3.0.3 on 2020-03-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonmodels',
            name='enabled_tests',
            field=models.ManyToManyField(through='modeler.TestsModels', to='modeler.Tests'),
        ),
        migrations.AddField(
            model_name='pythonmodels',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pythonmodels',
            name='score_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modeler.ScoresTypes'),
        ),
        migrations.DeleteModel(
            name='ModelsScores',
        ),
    ]
